name: JamAction Bot

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, synchronize]

jobs:
  github-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18'

    - name: Build and run Go script
      run: |
        cd github-bot
        go build -o github_bot cmd/main.go
        ./github_bot
      env:
        APP_ID: ${{ secrets.APP_ID }}
        INSTALLATION_ID: ${{secrets.INSTALLATION_ID}}
        PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
        JAMAI_KEY: ${{secrets.JAMAI_KEY}}
        JAMAI_PROJECT_ID: ${{secrets.JAMAI_PROJECT_ID}}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        GITHUB_EVENT_PATH: ${{ github.event_path }}
